version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.1
